name: Node CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: "node-ci-cd"
        path: "."
        format: "HTML"

    - name: Build Docker Image
      run: |
        docker build -t node-ci-cd:latest . || exit 0

    - name: Run Trivy Scan
      run: |
        echo "Running Trivy Scan"
        trivy image node-ci-cd:latest || exit 0

    - name: DockerHub Login
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin || exit 0

    - name: Push Image
      run: |
        docker push node-ci-cd:latest || exit 0
